name: Github Actions test
run-name: Log a message
on:
  push:
    branches:
      - main
jobs:
  Test-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This message occurs when you push"